name: IPTV Checker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check playlist exists
        run: |
          echo "Checking files..."
          ls -lah
          echo "Looking for ro.m3u..."
          test -f ro.m3u && echo "ro.m3u FOUND" || echo "ro.m3u MISSING"
